"""CLIP text definitions for the ImageNet-9 Backgrounds Challenge."""

# Keep this order synchronized with ImageNet9_Runs/imagenet9_data.py. The
# WeCLIP+ class files and model outputs use positional class indices.
_all_class_names = [
    "dog",
    "bird",
    "vehicle",
    "reptile",
    "carnivore",
    "insect",
    "instrument",
    "primate",
    "fish",
]

# These are the foreground concepts embedded by CLIP. Use the benchmark's
# broad class semantics rather than prompts tied to any particular background.
_all_new_class_names = [
    "dog",
    "bird",
    "vehicle",
    "reptile",
    "carnivore",
    "insect",
    "musical instrument",
    "primate",
    "fish",
]


# Generic scene, surface, structure, and support-object concepts. Foreground
# category names and close foreground synonyms are intentionally excluded so
# that a true ImageNet-9 object is not represented as background evidence.
BACKGROUND_CATEGORY = [
    # General context and photographic appearance.
    "background",
    "surroundings",
    "scenery",
    "landscape",
    "environment",
    "empty space",
    "blurred background",
    "bokeh background",
    "depth of field",
    "shadow",
    "reflection",
    "silhouette",
    # Ground and natural surfaces.
    "ground",
    "land",
    "soil",
    "dirt",
    "mud",
    "sand",
    "gravel",
    "pebbles",
    "stone",
    "rock",
    "boulder",
    "grass",
    "lawn",
    "moss",
    "leaf litter",
    "snow",
    "ice",
    "puddle",
    # Vegetation and outdoor regions.
    "tree",
    "tree trunk",
    "branch",
    "bark",
    "roots",
    "foliage",
    "leaves",
    "bush",
    "shrub",
    "hedge",
    "reeds",
    "flowers",
    "wildflowers",
    "forest",
    "woodland",
    "jungle",
    "field",
    "meadow",
    "prairie",
    "pasture",
    "farmland",
    "crop field",
    "orchard",
    "garden",
    # Sky, weather, and lighting.
    "sky",
    "cloud",
    "horizon",
    "sunlight",
    "sun glare",
    "shade",
    "fog",
    "mist",
    "haze",
    "rain",
    "snowfall",
    "overcast sky",
    "sunrise",
    "sunset",
    "night sky",
    # Water and coastal context.
    "water",
    "river",
    "stream",
    "creek",
    "lake",
    "pond",
    "ocean",
    "sea",
    "shore",
    "shoreline",
    "beach",
    "coast",
    "wetland",
    "marsh",
    "swamp",
    "waterfall",
    "waves",
    "ripples",
    "foam",
    "dock",
    "pier",
    # Terrain.
    "mountain",
    "hill",
    "valley",
    "ridge",
    "cliff",
    "canyon",
    "desert",
    "dune",
    "cave",
    # Roads and public infrastructure.
    "road",
    "street",
    "sidewalk",
    "path",
    "trail",
    "pavement",
    "asphalt",
    "concrete",
    "parking lot",
    "railway",
    "railroad track",
    "bridge",
    "tunnel",
    "curb",
    "guardrail",
    "streetlight",
    "utility pole",
    "power lines",
    "traffic sign",
    "billboard",
    # Buildings and structural elements.
    "building",
    "house",
    "apartment",
    "barn",
    "shed",
    "cabin",
    "warehouse",
    "factory",
    "wall",
    "brick wall",
    "stone wall",
    "fence",
    "gate",
    "door",
    "doorway",
    "window",
    "roof",
    "ceiling",
    "floor",
    "stairs",
    "railing",
    "balcony",
    "porch",
    "courtyard",
    # Indoor scenes.
    "room",
    "kitchen",
    "dining room",
    "living room",
    "bedroom",
    "office",
    "classroom",
    "workshop",
    "store",
    "museum",
    "stage",
    "auditorium",
    # Furniture, containers, and support objects.
    "table",
    "desk",
    "countertop",
    "shelf",
    "cabinet",
    "chair",
    "bench",
    "sofa",
    "bed",
    "plate",
    "bowl",
    "tray",
    "container",
    "basket",
    "box",
    "crate",
    "bag",
    "backpack",
    "cloth",
    "blanket",
    "cage",
    "enclosure",
    "aquarium tank",
    "terrarium",
    # Common materials and image clutter.
    "wood",
    "metal",
    "plastic",
    "glass",
    "brick",
    "tile",
    "fabric",
    "paper",
    "cardboard",
    "wire mesh",
    "rope",
    "netting",
    "sign",
    "label",
    "logo",
    "watermark",
    "text overlay",
]
